### ISSUE TITLE
Change text on Add On

### ISSUE THREAD

**Issue by overeha** [code4romania/emergency-news-addon#15]
Replace this text
”Coronavirus
Coronaviruses (CoV) are a large family of viruses that cause illness ranging from the common cold to more severe diseases”
with
”Informează-te din surse oficiale
Nu toate știrile care circulă pe internet sunt și corecte. Când citești informații despre subiectul pandemiei verifică informația cu sursele oficiale. Acestea sunt disponibile aici:”

![issue 1 coronavirus](https://user-images.githubusercontent.com/45068169/76698257-6fd5a500-66a9-11ea-96aa-4f76a7693a71.png)

**Comment by andreicristianpetcu** [comment]
The data is fake. Any change in this file https://github.com/code4romania/emergency-news-addon/blob/master/terms.json will be visible after 12h or after browser restart.
You can edit the json yourself.

**Comment by andreicristianpetcu** [comment]
As I understand it, this is the place where the real data is being populated. https://docs.google.com/spreadsheets/d/13hIjcFFJoPNq0X9ijU0oNaszstS2ZXz45gS7GHcwVRU/htmlview#gid=0

**Comment by catileptic** [comment]
Closing this this is fixed
