### ISSUE TITLE
Change branding 

### ISSUE THREAD

**Issue by overeha** [code4romania/emergency-news-addon#19]
We need to replace the Gov logo with this one. 

![Sigla_Guvern_+_ADR](https://user-images.githubusercontent.com/45068169/76702730-dd4afb00-66d4-11ea-9dde-0b50a827b8ed.png)

**Comment by andreicristianpetcu** [comment]
![stiri test_hotarari(iPhone 6_7_8)](https://user-images.githubusercontent.com/922368/76704331-e80b8d00-66e0-11ea-8ea6-ef98d8c81a3e.png)

**Comment by andreicristianpetcu** [comment]
E pentru mobile sau și pt desktop?
Ce face burger menu din dreapta sus?
De unde e iconița asociată textului?
Textul pare super generic. E doar un mocup pt tooltip?
Lunkurile nu apar în mocup, ele rămân, nu?
