### ISSUE TITLE
Credentiale Chrome Web Store si Cont Code4Ro pe AMO

### ISSUE THREAD

**Issue by andreicristianpetcu** [code4romania/emergency-news-addon#2]
Pe Firefox il public pe contul meu si apoi adaug Code4Ro contribuitor. cum arata aici:

https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/
![image](https://user-images.githubusercontent.com/922368/76618240-c370b300-6530-11ea-8b77-db8cb38d665b.png)

**Comment by catileptic** [comment]
<img width="443" alt="Screenshot 2020-03-14 at 14 21 14" src="https://user-images.githubusercontent.com/14028425/76681751-0f8a2900-65ff-11ea-8974-491b133f3ed6.png">
