### ISSUE TITLE
Popup is broken on the Google info box 

### ISSUE THREAD

**Issue by gcbirzan** [code4romania/emergency-news-addon#27]
https://i.imgur.com/zVESO77.png

That's supposed to be the coronavirus popup, it's just not displayed properly. Still doesn't  work on the second row:  https://i.imgur.com/UzZTPGr.png

**Comment by andreicristianpetcu** [comment]
link spre site?

**Comment by gcbirzan** [comment]
Google: "coronavirus symptoms"

**Comment by andreicristianpetcu** [comment]
@gcbirzan please re-test with version 1.2.1 in addons.mozilla.org. Chrome will take a while.
