### ISSUE TITLE
Please also create App for Android

### ISSUE THREAD

**Issue by web-sys1** [code4romania/emergency-news-addon#37]
It's important to tell users regarding this development of the app in Google Play. The next step is to create reilable application for Android regarding the COVID-19 in Romania. I need to make it.

**Comment by catileptic** [comment]
@web-sys1 - Firefox and Chrome are both browsers that you can use on Android phones and both of these have a working _Știri Oficiale_ extension. What is, in your view, the reasoning behind creating a separate mobile-only application?

**Comment by web-sys1** [comment]
> @web-sys1 - Firefox and Chrome are both browsers that you can use on Android phones and both of these have a working _Știri Oficiale_ extension. What is, in your view, the reasoning behind creating a separate mobile-only application?

Both Chrome and Firefox are same extension. Next step to Code4 is to develop _Știri Oficiale_ for Android. I see.  But, Google Play also needs app.

**Comment by andreicristianpetcu** [comment]
Actually only Firefox for Android supports extensions, including ours. We test on Android before each new version is released. Here is a print screen.

![Screenshot_20200320-113156_Firefox](https://user-images.githubusercontent.com/922368/77186511-aa8d7200-6adb-11ea-8060-555d1a2010e2.png)

Chrome does not support extensions on mobile.

What need would an app satisfy that a Site+extension does not?

**Comment by web-sys1** [comment]
> What need would an app satisfy that a Site+extension does not?

An application based on COVID-19 official news. You can include features in app if needed. I suggest you to discuss the development to this project.

**Comment by andreicristianpetcu** [comment]
We build things based on needs. If there is no clear need for an app, we will not build it. If there is a clear need, we can try to see how we can satisfy it with the projects we already built.

If you don't have a clear need, I will close the issue. "I need an app" is not a valid request. "I need to do X and neither the site nor the extension can help" me, IS a valid request.

**Comment by web-sys1** [comment]
> We build things based on needs. If there is no clear need for an app, we will not build it. If there is a clear need, we can try to see how we can satisfy it with the projects we already built.
> 
> If you don't have a clear need, I will close the issue. "I need an app" is not a valid request. "I need to do X and neither the site nor the extension can help" me, IS a valid request.

OK. I need to do an _Știri Oficiale COVID-19_ app and neither the site nor the extension can help.

**Comment by andreicristianpetcu** [comment]
You are not asking us to solve a problem, you want us to implement something as you want it. None of your comments mention a real issue.

Sure, an android app would be cool, but would it be useful? I'm a volunteer here, tring to implement low effort + high value stuff. An android app would not solve any isdues beside "we don't have an android app".

**Comment by web-sys1** [comment]
Repoen.

sâm., 21 mar. 2020, 19:48 Andrei Petcu <notifications@github.com> a scris:

**Comment by web-sys1** [comment]
> You are not asking us to solve a problem, you want us to implement something as you want it. None of your comments mention a real issue.
> 
> Sure, an android app would be cool, but would it be useful? I'm a volunteer here, tring to implement low effort + high value stuff. An android app would not solve any isdues beside "we don't have an android app".

Please clarify; I asked you to build an adroid app. But, how to reach you?

**Comment by andreicristianpetcu** [comment]
We are not having any plans to build an Android app.
