### ISSUE TITLE
Latest update changes text on webpage

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/emergency-news-addon#39]
This issue replicates on http://test.cemafac.ro

Some keywords are being duplicated on the webpage - checkout `Transmitere` that appears on the other sections as well, e.g. `Cum ne protejam`

**Comment by andreicristianpetcu** [comment]
https://test.cemafac.ro/pentru-cei-care-ofera-ajutor

**Comment by andreicristianpetcu** [comment]
Fixed
![fixed](https://user-images.githubusercontent.com/922368/77250724-75eff680-6c52-11ea-990b-091681d580b3.gif)
